package com.novaclaw.app.plugins

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import com.getcapacitor.JSObject
import com.getcapacitor.Plugin
import com.getcapacitor.PluginCall
import com.getcapacitor.PluginMethod
import com.getcapacitor.annotation.CapacitorPlugin
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * SecureKeyPlugin - Manages the ZEN_API_KEY in Android Keystore.
 *
 * Flow:
 * 1) On first launch, the app reads the obfuscated blob embedded in assets
 *    (generated by scripts/embedKey.mjs) and decodes it in memory.
 * 2) Immediately re-encrypts it with an AES key generated in the
 *    Android Keystore (hardware-backed if the device supports it).
 * 3) Saves the encrypted blob in SharedPreferences.
 * 4) On subsequent launches, it only decrypts when the agent plugin
 *    needs it to call the Zen endpoint.
 *
 * IMPORTANT: Ideally, the JS frontend NEVER receives the key in cleartext.
 * The Agent plugin should make the HTTP call to Zen directly from
 * Kotlin and return only the response content to the WebView.
 * TODO: Long-term, move the Zen API call to a native Kotlin plugin
 *       so the key never leaves the native layer.
 */
@CapacitorPlugin(name = "SecureKey")
class SecureKeyPlugin : Plugin() {

    companion object {
        private const val KEYSTORE_ALIAS = "novaclaw.zenkey.v1"
        private const val PREF_NAME = "novaclaw.secure"
        private const val PREF_KEY_ENCRYPTED = "zen_encrypted"
        private const val PREF_KEY_IV = "zen_iv"
    }

    @PluginMethod
    fun store(call: PluginCall) {
        val plaintext = call.getString("value")
        if (plaintext.isNullOrBlank()) {
            call.reject("value is required")
            return
        }
        try {
            val secretKey = getOrCreateSecretKey()
            val cipher = Cipher.getInstance("AES/GCM/NoPadding")
            cipher.init(Cipher.ENCRYPT_MODE, secretKey)
            val iv = cipher.iv
            val encrypted = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))

            val prefs = context.getSharedPreferences(PREF_NAME, 0)
            prefs.edit()
                .putString(PREF_KEY_ENCRYPTED, Base64.encodeToString(encrypted, Base64.NO_WRAP))
                .putString(PREF_KEY_IV, Base64.encodeToString(iv, Base64.NO_WRAP))
                .apply()
            call.resolve(JSObject().apply { put("success", true) })
        } catch (e: Exception) {
            call.reject("Failed to store key: ${e.message}", e)
        }
    }

    @PluginMethod
    fun has(call: PluginCall) {
        val prefs = context.getSharedPreferences(PREF_NAME, 0)
        val present = prefs.contains(PREF_KEY_ENCRYPTED) && prefs.contains(PREF_KEY_IV)
        call.resolve(JSObject().apply { put("has", present) })
    }

    /**
     * Retrieves the decrypted API key for use by the in-app agent.
     * This is the only JS-accessible way to get the key - it is needed
     * so the agent can call the Zen API from the WebView.
     */
    @PluginMethod
    fun get(call: PluginCall) {
        try {
            val value = getInternal()
            call.resolve(JSObject().apply { put("value", value) })
        } catch (e: Exception) {
            call.reject("Failed to get key: ${e.message}", e)
        }
    }

    /**
     * Internal-only key retrieval - NOT exposed to JS via @PluginMethod.
     * Other Kotlin plugins should call this directly.
     */
    fun getInternal(): String {
        val prefs = context.getSharedPreferences(PREF_NAME, 0)
        val encryptedB64 = prefs.getString(PREF_KEY_ENCRYPTED, null) ?: return ""
        val ivB64 = prefs.getString(PREF_KEY_IV, null) ?: return ""

        val encrypted = Base64.decode(encryptedB64, Base64.NO_WRAP)
        val iv = Base64.decode(ivB64, Base64.NO_WRAP)

        val keyStore = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        val secretKey = keyStore.getKey(KEYSTORE_ALIAS, null) as SecretKey

        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, secretKey, GCMParameterSpec(128, iv))
        val decrypted = cipher.doFinal(encrypted)
        return String(decrypted, Charsets.UTF_8)
    }

    private fun getOrCreateSecretKey(): SecretKey {
        val keyStore = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        val existing = keyStore.getKey(KEYSTORE_ALIAS, null)
        if (existing != null) return existing as SecretKey

        val kg = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore")
        val spec = KeyGenParameterSpec.Builder(
            KEYSTORE_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            .build()
        kg.init(spec)
        return kg.generateKey()
    }
}
